# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class Ui_unaUI(object):
    def setupUi(self, MainWindow):
        width = 800
        height = 550
        gheight = 450
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(width, height)
        #self.setFixedSize(width, height)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(0, 0, width, gheight))
        self.gif.setObjectName("gif")

        MainWindow.setCentralWidget(self.centralwidget)

        self.movie = QMovie("./Assets/una.gif")
        self.gif.setMovie(self.movie)
        self.movie.start()

        self.reply = QtWidgets.QLabel(self.centralwidget)
        self.reply.setGeometry(QtCore.QRect(0, gheight, width, 200))
        font = QtGui.QFont()
        font.setFamily("DIN Alternate")
        self.reply.setFont(font)
        self.reply.setStyleSheet(
            "background:rgb(0, 0, 0); color: white; font-size:20px; padding-top:28px;")
        self.reply.setAlignment(QtCore.Qt.AlignHCenter)
        self.reply.setObjectName("reply")
        self.reply.setText("Hi, I'm here to help ! Ask me anything")
        MainWindow.setCentralWidget(self.centralwidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_unaUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
